# Generated by Django 6.0.4 on 2026-04-18 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_empresa_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Banco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("agencia", models.CharField(blank=True, max_length=20)),
                ("conta", models.CharField(blank=True, max_length=20)),
                (
                    "saldo_inicial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.empresa"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LancamentoBancario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("descricao", models.CharField(max_length=255)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("entrada", "Entrada"), ("saida", "Saída")],
                        max_length=10,
                    ),
                ),
                (
                    "classificacao",
                    models.CharField(
                        choices=[
                            ("despesa", "Despesa"),
                            ("investimento", "Investimento"),
                            ("adiantamento_socio", "Adiantamento de Sócio"),
                            ("distribuicao_lucro", "Distribuição de Lucro"),
                            ("outros", "Outros"),
                        ],
                        max_length=30,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "banco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lancamentos",
                        to="core.banco",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
