# Generated by Django 6.0.4 on 2026-04-18 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_banco_lancamentobancario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("codigo", models.CharField(blank=True, max_length=50)),
                (
                    "quantidade",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("unidade", models.CharField(default="un", max_length=20)),
                (
                    "preco_custo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "estoque_minimo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.empresa"
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.produto",
                    ),
                ),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="MovimentacaoEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("entrada", "Entrada"),
                            ("saida", "Saída"),
                            ("ajuste", "Ajuste"),
                        ],
                        max_length=10,
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=2, max_digits=14)),
                ("data", models.DateField()),
                ("observacao", models.CharField(blank=True, max_length=255)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimentacoes",
                        to="core.itemestoque",
                    ),
                ),
            ],
        ),
    ]
