# Generated by Django 6.0.4 on 2026-04-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_itemestoque_movimentacaoestoque"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("produto", "Produto Final"),
                    ("materia_prima", "Matéria Prima"),
                    ("embalagem", "Embalagem"),
                    ("tampa", "Tampa"),
                    ("rotulo", "Rótulo"),
                ],
                default="produto",
                max_length=20,
            ),
        ),
    ]
