# Generated by Django 6.0.4 on 2026-04-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_produto_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="preco_unitario",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="produto",
            name="quantidade",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="produto",
            name="unidade",
            field=models.CharField(default="un", max_length=20),
        ),
    ]
