# Generated by Django 6.0.4 on 2026-04-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_produto_preco_unitario_produto_quantidade_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="quantidade",
        ),
        migrations.AddField(
            model_name="produto",
            name="peso",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="produto",
            name="unidade",
            field=models.CharField(
                choices=[
                    ("ml", "ml"),
                    ("l", "L"),
                    ("g", "g"),
                    ("kg", "kg"),
                    ("pct", "pct"),
                    ("un", "un"),
                    ("cx", "cx"),
                    ("outro", "Outro"),
                ],
                default="un",
                max_length=20,
            ),
        ),
    ]
