# Generated by Django 6.0.4 on 2026-04-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_produto_quantidade_produto_peso_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="limite_alto",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AddField(
            model_name="produto",
            name="limite_critico",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AddField(
            model_name="produto",
            name="limite_medio",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
