# Generated by Django 6.0.4 on 2026-04-21 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_produto_limite_alto_produto_limite_critico_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="limite_alto",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="limite_critico",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="limite_medio",
        ),
        migrations.CreateModel(
            name="ProdutoMateriaPrima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.empresa"
                    ),
                ),
                (
                    "materia_prima",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usado_em",
                        to="core.produto",
                    ),
                ),
                (
                    "produto_final",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materias_primas",
                        to="core.produto",
                    ),
                ),
            ],
        ),
    ]
