# Generated by Django 6.0.4 on 2026-04-25 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_categoriaproduto_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="subcategoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="produtos",
                to="core.subcategoriaproduto",
            ),
        ),
    ]
