# Generated by Django 6.0.4 on 2026-04-26 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_itemestoque_produto"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="produtomateriaprima",
            unique_together={("empresa", "produto_final", "materia_prima")},
        ),
    ]
