# Generated by Django 6.0.4 on 2026-05-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_remove_lancamentobancario_classificacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lancamentobancario",
            name="classificacao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("despesa", "Despesa"),
                    ("investimento", "Investimento"),
                    ("adiantamento_socio", "Adiantamento de Sócio"),
                    ("distribuicao_lucro", "Distribuição de Lucro"),
                    ("outros", "Outros"),
                ],
                default="outros",
                max_length=30,
            ),
        ),
    ]
