# Generated by Django 6.0.4 on 2026-05-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_add_classificacao_lancamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtomateriaprima",
            name="unidade",
            field=models.CharField(
                choices=[
                    ("ml", "ml"),
                    ("l", "L"),
                    ("g", "g"),
                    ("kg", "kg"),
                    ("pct", "pct"),
                    ("un", "un"),
                    ("cx", "cx"),
                    ("outro", "Outro"),
                ],
                default="un",
                max_length=20,
            ),
        ),
    ]
