# Generated by Django 6.0.4 on 2026-05-12 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_produtomateriaprima_unidade"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FichaProducao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField(editable=False)),
                ("data", models.DateField()),
                (
                    "descricao_produto",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Descrição do produto (se não cadastrado)",
                    ),
                ),
                (
                    "quantidade_produzida",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "unidade_produzida",
                    models.CharField(
                        choices=[
                            ("ml", "ml"),
                            ("l", "L"),
                            ("g", "g"),
                            ("kg", "kg"),
                            ("pct", "pct"),
                            ("un", "un"),
                            ("cx", "cx"),
                            ("outro", "Outro"),
                        ],
                        default="un",
                        max_length=20,
                    ),
                ),
                (
                    "tanques",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Tanques utilizados"
                    ),
                ),
                (
                    "maquina",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Máquina utilizada"
                    ),
                ),
                (
                    "responsavel",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Responsável"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.empresa"
                    ),
                ),
                (
                    "produto_final",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fichas_producao",
                        to="core.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ficha de Produção",
                "verbose_name_plural": "Fichas de Produção",
                "ordering": ["-data", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ItemFichaProducao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("insumo", "Insumo"),
                            ("embalagem", "Embalagem"),
                            ("tampa", "Tampa"),
                            ("rotulo", "Rótulo"),
                        ],
                        default="insumo",
                        max_length=20,
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Descrição (se não cadastrado)",
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "unidade",
                    models.CharField(
                        choices=[
                            ("ml", "ml"),
                            ("l", "L"),
                            ("g", "g"),
                            ("kg", "kg"),
                            ("pct", "pct"),
                            ("un", "un"),
                            ("cx", "cx"),
                            ("outro", "Outro"),
                        ],
                        default="un",
                        max_length=20,
                    ),
                ),
                (
                    "ficha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="core.fichaproducao",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="itens_ficha",
                        to="core.produto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerdaProducao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Descrição (se não cadastrado)",
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "unidade",
                    models.CharField(
                        choices=[
                            ("ml", "ml"),
                            ("l", "L"),
                            ("g", "g"),
                            ("kg", "kg"),
                            ("pct", "pct"),
                            ("un", "un"),
                            ("cx", "cx"),
                            ("outro", "Outro"),
                        ],
                        default="un",
                        max_length=20,
                    ),
                ),
                (
                    "motivo",
                    models.TextField(blank=True, verbose_name="Motivo da perda"),
                ),
                (
                    "ficha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perdas",
                        to="core.fichaproducao",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="perdas_producao",
                        to="core.produto",
                    ),
                ),
            ],
        ),
    ]
